### ISSUE TITLE
Quebra de Linha

### ISSUE THREAD

**Issue by andersonbosing** [Elotech-Dev/SITS#5]
Qual carácter de quebra de linha devo enviar para que o projeto entenda ?

**Comment by ivanmarceloferreira** [comment]
Boa tarde, Anderson

A princípio era uma configuração do Castor que não estava permitindo a quebra de linha. Foi feito um pull request com a correção e agora você pode mandar a quebra de linha normalmente (com enter mesmo) ou usando código HTML `&#10;&#13;`.

**Comment by andersonbosing** [comment]
Boa Tarde Ivan, Obrigado!
